### ISSUE TITLE
No longer launches Gnome Version 3.32.2 (RHEL current build)

### ISSUE THREAD

**Issue by mo-g** [flathub/com.belmoussaoui.Authenticator#12]
```
$ flatpak run com.belmoussaoui.Authenticator 
2022-05-31T15:00:38.220866Z  INFO authenticator::application: Authenticator (com.belmoussaoui.Authenticator)
2022-05-31T15:00:38.220907Z  INFO authenticator::application: Version: 4.1.2 ()
2022-05-31T15:00:38.220916Z  INFO authenticator::application: Datadir: /app/share/authenticator
2022-05-31T15:00:38.225905Z  INFO authenticator::application: Migrating the secrets to the file backend
2022-05-31T15:00:38.248122Z ERROR authenticator::application: Failed to migrate your data Portal error Portal communication failed org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.portal.Secret' on object at path /org/freedesktop/portal/desktop
thread 'main' panicked at 'Failed to start a location service: Portal(PortalBus(MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.UnknownMethod")))), Some("No such interface 'org.freedesktop.portal.Secret' on object at path /org/freedesktop/portal/desktop"), Msg { type: Error, sender: UniqueName(Str(Borrowed(":1.81"))), reply-serial: 5, body: Signature: [
	s (115),
] })))', src/application.rs:328:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by ghost** [comment]
Having the same issue.

**Comment by bilelmoussaoui** [comment]
The latest release requires having xdg-desktop-portal installed, can you check which version you have installed?

**Comment by bilelmoussaoui** [comment]
https://github.com/bilelmoussaoui/oo7/pull/16 should fix the issue, I will merge it and do a new fix release of Authenticator later today.

**Comment by bilelmoussaoui** [comment]
I have published a new version that should fix the issue, please let me know how that goes.

**Comment by bilelmoussaoui** [comment]
It should be fixed now in 4.1.4, see https://gitlab.gnome.org/World/Authenticator/-/issues/332

**Comment by spr1t3-0** [comment]
It's giving me this error on bedrock linux:
```
2023-03-06T11:09:10.285664Z ERROR authenticator::application: Failed to migrate your data Portal error Portal request was cancelled
thread 'main' panicked at 'Failed to start a location service: Portal(CancelledPortalRequest)', src/application.rs:310:18
```

**Comment by mo-g** [comment]
> It's giving me this error on bedrock linux:
> 
> ```
> 2023-03-06T11:09:10.285664Z ERROR authenticator::application: Failed to migrate your data Portal error Portal request was cancelled
> thread 'main' panicked at 'Failed to start a location service: Portal(CancelledPortalRequest)', src/application.rs:310:18
> ```

That looks like a different error. You should open a new Issue!

**Comment by brantg** [comment]
> It's giving me this error on bedrock linux:
> 
> ```
> 2023-03-06T11:09:10.285664Z ERROR authenticator::application: Failed to migrate your data Portal error Portal request was cancelled
> thread 'main' panicked at 'Failed to start a location service: Portal(CancelledPortalRequest)', src/application.rs:310:18
> ```

Same result here on Gentoo.  Did you open a new Issue yet?
