### ISSUE TITLE
Support deb/snap/appimage

### ISSUE THREAD

**Issue by dnet890** [flathub/com.belmoussaoui.Authenticator#19]
Since flatpak format is broken (https://github.com/flathub/com.belmoussaoui.Authenticator/issues/16 ) & (https://github.com/flathub/com.belmoussaoui.Authenticator/issues/15) and possess lots of problems to many distros. Hence different packaging is needed to cover many distros. Is it possible to support deb/snap/appimage?

**Comment by bilelmoussaoui** [comment]
No
