### ISSUE TITLE
GitLab provider cannot import previous Authenticator entry

### ISSUE THREAD

**Issue by x80486** [flathub/com.belmoussaoui.Authenticator#2]
I exported this entry from the previous Authenticator:

```json
{"secret": "********", "label": "office", "period": 30, "digits": 6, "type": "OTP", "algorithm": "SHA1",
 "thumbnail": "Default", "last_used": 0, "tags": ["GitLab"]},
```

Now when I'm trying to insert the entry again, it tells me the token is invalid:

![image](https://user-images.githubusercontent.com/34633617/106409284-32d3e780-640e-11eb-982d-1afe3eb197b3.png)

> This is a GitLab Enterprise instance the company (I work for) hosts on their own — not sure if that's relevant.

**Comment by x80486** [comment]
It doesn't work either with a GitLab.com account — what I normally use. I just tested it trying to add my personal GitLab TOTP key.

**Comment by bilelmoussaoui** [comment]
there's a gitlab repo, for app issues.

**Comment by bilelmoussaoui** [comment]
I can reproduce this one, I will have a look and do a patch release as soon as possible

**Comment by bilelmoussaoui** [comment]
a workaround for now, write the token in uppercase

**Comment by bilelmoussaoui** [comment]
Should be fixed in https://github.com/flathub/com.belmoussaoui.Authenticator/commit/3f5462ccf2765e68697adfedf29ef987406bbadc
