### ISSUE TITLE
Failed to initialize GTK on X11

### ISSUE THREAD

**Issue by extraymond** [flathub/com.belmoussaoui.Authenticator#21]
## info

**operating system**: ubuntu 22.04, xorg login session
**expected result**: able to launch the app
**steps to reproduce**:
1. login to wayland session
2. able to launch the app 
3. login to xorg session
4. launch the app via terminal returns `thread 'main' panicked at 'failed to init gtk: BoolError { message: "Failed to initialize GTK", filename: "/run/build/authenticator/vendor/gtk4/src/rt.rs", function: "gtk4::rt", line: 153 }', src/main.rs:29:17`
5. by setting **WAYLAND_DISPLAY=** as env vars the app is able to launch.

Given how this problem can be managed by the env_var, this seems to be related to how gtk detects whether it's under wayland or xorg, hope this helps.

**Comment by A6GibKm** [comment]
This is unrelated to the app, it is most likely an issue on the host, please report it to your distribution as I cannot reproduce the problem.
