### ISSUE TITLE
I have error when im install from flatpak

### ISSUE THREAD

**Issue by Devious3901** [flathub/com.belmoussaoui.Authenticator#24]
Im installed from flatpak ver 4
and try to run it, and i have this problem
![image](https://github.com/flathub/com.belmoussaoui.Authenticator/assets/103393069/cf45080a-133c-417b-9f39-b235f20f3288)
help me please! step by step, because im noob at Linux

**Comment by bilelmoussaoui** [comment]
Something is broken on your distro causing the portal to not start properly. I would reach out to your distribution support instead.

**Comment by Devious3901** [comment]
> 

But from Synapse your ver 3 Auth works well, but i cant import json file
Im installed yesterday flatpak ver 4, its works well, but now im trying to reinstall and i have this error

**Comment by bilelmoussaoui** [comment]
Try restarting your machine, nothing I can help you fix as the app expects things to work on your machine...

**Comment by Devious3901** [comment]
> Try restarting your machine, nothing I can help you fix as the app expects things to work on your machine...

![image](https://github.com/flathub/com.belmoussaoui.Authenticator/assets/103393069/ffdf7fa0-8f9e-497e-b9ba-66dd5c47e0d8)
how i can add steam on ur 2fa? i dont mind, tbh, because Steam connect only to Steam Guard on phone?

**Comment by bilelmoussaoui** [comment]
There is some way to retrieve the steam token but no documented process by steam itself that is why it is not documented on the app itself.
