### ISSUE TITLE
No camera found

### ISSUE THREAD

**Issue by adrianinsaval** [flathub/com.belmoussaoui.Authenticator#25]
Can't scan QR image with webcam despite allowing camera and all devices access with flatseal:
![image](https://github.com/flathub/com.belmoussaoui.Authenticator/assets/36372335/0bf3b09f-5589-42f5-8321-3394318468f2)

**Comment by bilelmoussaoui** [comment]
That could mean a libcamera pipewire plugin missing or something like that.
