### ISSUE TITLE
Quits (crashes?) when pressing "Add" button for GitHub 2FA

### ISSUE THREAD

**Issue by ell1e** [flathub/com.belmoussaoui.Authenticator#27]
I just tested out GNOME authenticator, when I press the "Add" button in the new account dialog for a GitHub account after entering the account name and token, it freezes for a second or so and then all windows just disappear. When I reopen it, no account was added, so I assume it just crashed. I tried multiple times, the same thing happens every time.

**Version affected:** com.belmoussaoui.Authenticator 4.4.0 (installed via Flatpak from flathub)

**Tested on distribution:** postmarketOS 23.06

**Comment by bilelmoussaoui** [comment]
It looks like a broken keyring to me, would need a backtrace otherwise this report is useless
