### ISSUE TITLE
Large mouse size on wayland

### ISSUE THREAD

**Issue by 2GetApp** [flathub/com.belmoussaoui.Authenticator#31]
If Authenticator is running on wayland, the mouse size becomes larger when entering the window of Authenticator.
It works fine if it is running on x11.

**Comment by 2GetApp** [comment]
To reproduce:
`flatpak run --socket=wayland --nosocket=x11 --nosocket=fallback-x11 com.belmoussaoui.Authenticator` will produce larger mouse.

`flatpak run --nosocket=wayland --socket=x11 com.belmoussaoui.Authenticator` works fine.

**Comment by bilelmoussaoui** [comment]
That is a compositor issue.
